### ISSUE TITLE
Enhancement!

### ISSUE THREAD

**Issue by Ndegwadavid** [IamTabitha/Pizza-palace#1]
what happens after the POST request is made?
Suggestions: is you can add some javascript functionality for like "order successfully received"
i.e if you havent configured the backend functionality and the databases schemas.
![Screenshot_2023-07-21_12_23_06](https://github.com/IamTabitha/Pizza-palace/assets/107948989/791834ef-7762-4198-8f7d-cb58f84f800d)

Also the HTML attributes to autoreset to NULL in the order section.

I love the project.Keep up.

**Comment by Ndegwadavid** [comment]
i can help in adding more functionalities id you like?
but in mean time i will close the #enhancement issue. Maybe it was not intended to be modified.
Happy coding .

**Comment by IamTabitha** [comment]
Hi, thank you for raising the issue , I will work on it this week.

**Comment by Ndegwadavid** [comment]
Yeah sure no problem.:) 
its a good project and am following along

**Comment by Ndegwadavid** [comment]
Happy coding.
